apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: frontend-developer
  namespace: webapp
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list"]
  resourceNames: ["frontend-<pod-id>"] #insert frontend pod id here
