apiVersion: v1
kind: Pod
metadata:
  name: large-pod
  namespace: admission-test
spec:
  containers:
  - name: large-container
    image: busybox
    resources:
      requests:
        memory: "2Gi" # Exceeds the 1Gi limit
        cpu: "2" # Exceeds the 1 CPU limit
      limits:
        memory: "4Gi" # Exceeds the 2Gi limit
        cpu: "4" # Exceeds the 2 CPU limit
    command: ["sh", "-c", "sleep 3600"]
